#+title:     ¿Por que es importante la normalización de bases de datos?
#+author:    Oshiro Arika
#+email:     orihsoarika@gmail.com
#+html_head: <script src="./main.js"></script> <link rel="stylesheet" type="text/css" href="./style.css"/>

* ¿Que es la normalización de Bases de Datos?
La normalización de una base de datos es un paso esencial tras su creación, por que evita cualquier tipo de anomalía, redundancia y borrado que pueda haber en el diseño de tablas y en la relación entre la información.

– /Pero... ¿Para qué tenemos que normalizar una base de datos?/

Pues para evitar que uno o mas datos estén duplicados en la tabla de una base de datos, o sea, no pueden haber mas dos María con el mismo ID. O datos que no estén en uso.

Esto y otros factores pueden causar confusión en una base de datos tanto a ti como a un Sistema Gestor de Bases de Datos (SGBD), ademas de que dicha base de datos sera mas pesada, lenta y difícil de manejar.

Una normalización de base de datos, sobretodo para empresas B2B, requiere una importante inversión de tiempo y esfuerzo, debido a que contiene muchos datos complejos.

A pesar de que /—En algunos casos—/ las bases de datos normalizadas hacen los procesos mas lentos, aun así merece la pena hacer la normalización para evitar problemas a futuro.
* Objetivos de la normalización de bases de datos
- Corregir datos duplicados y anomalías en la base de datos.
- Evitar la creación y actualización de relaciones y dependencias no deseadas entre datos.
- Prevenir la eliminación de datos accidentales
- Optimizar el uso de almacenamiento.
- Reducir el tiempo y complejidad de revisión cuando se requiere introducir nuevos tipos de datos.
- Facilitar el acceso e interpretación de los datos a los usuarios y aplicaciones que los usan.
* ¿Por que es importante normalizar una base de datos?
Como lo que se escribió antes, ayuda a las empresas e instituciones a organizar, consultar y mantener de forma mas eficaz grandes volúmenes de datos complejos, interrelaciones y dinámicos.

Los datos sin normalizar y desordenados dificultan la compresión y mecánica, afectando negativamente la funcionalidad de las características y funciones.  Por ejemplo, al buscar "Google Chrome" es posible que no muestre los mismos resultados que "Chrome" debido a incoherencias en la representación de los datos.  Esto merma la precisión y eficacia de los procesos de consulta, lo que conduce a resultados inadecuados y conexiones incompletas.

Por eso, lo normalización hace que la búsqueda de términos o entidades especificas sea mas eficiente y precisa.  Las conexiones entre elementos de datos relacionados se refuerzan, lo que permite mejorar la recuperación y el análisis de la información.

Ademas, esta practica tiene implicancias mas amplias para la funcionalidad y el rendimiento de las bases de datos.  Aquellos normalizados son mas fáciles de ordenar, filtrar y analizar, lo que facilita su exploración y reconocimiento de patrones.  Con una menor cantidad de columnas y una organización mejorada, los usuarios acceden a mas registros en una sola pagina, mayor visualización, compresión y reconocimiento de patrones.

Por el lado de la experiencia del usuario, simplifica los procesos, permitiéndoles contar fácilmente con la información y modificarla, al tiempo que garantiza la coherencia, la precisión y la ausencia de contenidos duplicados o redundancias.  Así, múltiples personas pueden leer, interpretar y confiar en los registros presentados.

* Fuentes
- https://blog.saleslayer.com/es/por-que-es-importante-la-normalizacion-de-base-de-datos
- https://www.ibm.com/es-es/think/topics/database-normalization
- https://blog.invgate.com/es/normalizacion-de-base-de-datos
